remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Kleine Hof
description: Abenteuer f√ºr die Kleinen in Berlin
locale: en-GB
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Site settings
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
